clientes:
    pattern:  /
    defaults: { _controller: "JoeZafiroBundle:Clientes:index" }

clientes_show:
    pattern:  /{id}/show
    defaults: { _controller: "JoeZafiroBundle:Clientes:show" }

clientes_new:
    pattern:  /new
    defaults: { _controller: "JoeZafiroBundle:Clientes:new" }

clientes_create:
    pattern:  /create
    defaults: { _controller: "JoeZafiroBundle:Clientes:create" }
    requirements: { _method: post }

clientes_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JoeZafiroBundle:Clientes:edit" }

clientes_update:
    pattern:  /{id}/update
    defaults: { _controller: "JoeZafiroBundle:Clientes:update" }
    requirements: { _method: post|put }

clientes_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JoeZafiroBundle:Clientes:delete" }
    requirements: { _method: post|delete }

clientes_toggle_salida:
    pattern:  /{id}/toggle_salida
    defaults: { _controller: "JoeZafiroBundle:Clientes:toggle_salida" }

clientes_toggle_proxy:
    pattern:  /{id}/toggle_proxy
    defaults: { _controller: "JoeZafiroBundle:Clientes:toggle_proxy" }    
clientes_toggle_estado:
    pattern:  /{id}/toggle_estado
    defaults: { _controller: "JoeZafiroBundle:Clientes:toggle_estado" }